import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import '../src/app/styles/variables/globals.css';
import { Providers } from './providers';

const jetbrains = JetBrains_Mono({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-jetbrains',
	display: 'swap'
});

const hack = localFont({
	src: [
		{
			path: '../public/fonts/Hack-Regular.woff2',
			weight: '400',
			style: 'normal'
		},
		{
			path: '../public/fonts/Hack-Bold.woff2',
			weight: '700',
			style: 'normal'
		},
		{
			path: '../public/fonts/Hack-Italic.woff2',
			weight: '400',
			style: 'italic'
		}
	],
	variable: '--font-hack',
	display: 'swap'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${hack.variable} ${jetbrains.variable}`}
		>
			<body id="root">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
